---
- name: Copy plugin checker groovy script
  sudo: yes
  copy: src=check_plugin.groovy dest={{ jenkins.dest }}/check_plugin.groovy mode=0440

- name: Check plugins
  sudo: yes
  shell: java -jar {{ jenkins.cli_dest }} -s http://localhost:8080/ groovy = < {{ jenkins.dest }}/check_plugin.groovy {{item}}
  when: plugins is defined
  with_items: plugins
  register: check_plugins

- name: Install plugins
  sudo: yes
  shell: java -jar {{ jenkins.cli_dest }} -s http://localhost:8080/ install-plugin {{item.item}}
  when: item.stdout.find('false') != -1
  with_items: check_plugins.results
  notify:
    - 'Restart Jenkins'

- name: List plugins to be updated
  sudo: yes
  action: shell java -jar {{ jenkins.cli_dest }} -s http://localhost:8080 list-plugins | grep ')$' | cut -f 1 -d ' ' | sed ':a;N;$!ba;s/\n/ /g'
  register: plugins_updates

- name: Update plugins
  sudo: yes
  action: command java -jar {{ jenkins.cli_dest }} -s http://localhost:8080 install-plugin {{ plugins_updates.stdout }}
  when: plugins_updates.stdout != ''
  notify:
    - 'Restart Jenkins'
